services:
  postgres:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: windows
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql